"""init

Revision ID: 15bac2218b71
Revises: 
Create Date: 2024-04-03 17:00:12.647351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bac2218b71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_id', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('zcta', sa.String(), nullable=True),
    sa.Column('parent_zcta', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('density', sa.String(), nullable=True),
    sa.Column('county_fips', sa.String(), nullable=True),
    sa.Column('county_name', sa.String(), nullable=True),
    sa.Column('county_weights', sa.String(), nullable=True),
    sa.Column('county_names_all', sa.String(), nullable=True),
    sa.Column('county_fips_all', sa.String(), nullable=True),
    sa.Column('imprecise', sa.String(), nullable=True),
    sa.Column('military', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat', 'lng', name='coordinates')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('points')
    # ### end Alembic commands ###
